blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns = [
    path('', views.all_blog, name='all_blog'),
    path('<int:blog_id>/', views.detail, name='detail'),

]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path,include

from portfolio import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=200)
    Description = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    Description = models.CharField(max_length=250, )
    images = models.ImageField(upload_to='portfolio/iamge')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


def all_blog(request):
    blogs = Blog.objects.order_by('-date')[:5]
    return render(request, 'blog/all_blog.html', {'blogs': blogs})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project


# Create your views here.

def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

blog/templates/blog/all_blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>all_blog</title>
</head>
<body>

<h1>alimomeni</h1>
<h2>ali writtern {{ blogs.count }} blog{{ blogs.count|pluralize }} </h2>
{% for blog in blogs %}
    <a href="{% url 'blog:detail' blog.id %}"><h2> {{ blog.title }} </h2></a>
    <br>
    <h5>   {{ blog.date|date:'M d Y' }} </h5>
    <br>
    <p>{{ blog.Description|truncatechars:100 }}</p>
    <br>
{% endfor %}
</body>
</html>

blog/templates/blog/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{{ blog.title}}
<br>
<br>
{{ blog.Description }}
</body>
</html>

portfolio/templates/portfolio/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home</title>
</head>
<body>
<h1>ali project</h1>


{% load static %}
<ol>
    <li><a href="{% url 'blog:all_blog' %}">Blog</a></li>
    <li><a href="{% static '/portfolio/a.pdf' %}">pdf</a></li>
</ol>



<br>

<img src="{% static '/portfolio/ali.jpg' %}" height="300" width="400">
<br>

{% for project in projects %}
    {{ project.title }}
    <br>
    {{ project.Description }}
    <br>

    <img src="{{ project.images.url }}" width="350" height="250">
    <br>
    {% if project.url %}
        <a href="{{ project.url }}">link google</a>
    {% endif %}
    <br>
{% endfor %}

</body>
</html>